HEATING_CHOICES = (
    ("NO", "No Heating"),
    ("AC", "Air Conditioner heating"),
    ("GAS", "Natural Gas heating"),
    ("STOVE", "Fire Place heating"),
    ("ELECTRIC", "Electric Boiler heating"),
)


PROPERTY_TYPES = (
    ("APARTMENT", "Apartment"),
    ("COMMERS", "Commercial unit"),
    ("LAND", "Land"),
    ("BUILDING", "Building"),
    ("FARM HOUSE", "Farm house"),
    ("UNDER CONSTRUCTION", "Under construction"),
)

DEAL_TYPES = (
    ("SALE", "SALE"),
    ("RENT", "RENT"),
)


IL_LIST = (
    ("Ağrı", "Ağrı"),
    ("Adana", "Adana"),
    ("Adıyaman", "Adıyaman"),
    ("Aydın", "Aydın"),
    ("Aksaray", "Aksaray"),
    ("Amasya", "Amasya"),
    ("Ankara", "Ankara"),
    ("Antalya", "Antalya"),
    ("Ardahan", "Ardahan"),
    ("Artvin", "Artvin"),
    ("Afyonkarahisar", "Afyonkarahisar"),
    ("Bayburt", "Bayburt"),
    ("Balıkesir", "Balıkesir"),
    ("Bartın", "Bartın"),
    ("Batman", "Batman"),
    ("Bilecik", "Bilecik"),
    ("Bingöl", "Bingöl"),
    ("Bitlis", "Bitlis"),
    ("Bolu", "Bolu"),
    ("Burdur", "Burdur"),
    ("Bursa", "Bursa"),
    ("Van", "Van"),
    ("Gaziantep", "Gaziantep"),
    ("Giresun", "Giresun"),
    ("Gümüşhane", "Gümüşhane"),
    ("Denizli", "Denizli"),
    ("Diyarbakır", "Diyarbakır"),
    ("Düzce", "Düzce"),
    ("Zonguldak", "Zonguldak"),
    ("İzmir", "İzmir"),
    ("Yozgat", "Yozgat"),
    ("Kayseri", "Kayseri"),
    ("Karabük", "Karabük"),
    ("Karaman", "Karaman"),
    ("Kars", "Kars"),
    ("Kastamonu", "Kastamonu"),
    ("Kahramanmaraş", "Kahramanmaraş"),
    ("Kilis", "Kilis"),
    ("Kocaeli", "Kocaeli"),
    ("Konya", "Konya"),
    ("Kırklareli", "Kırklareli"),
    ("Kırşehir", "Kırşehir"),
    ("Kırıkkale", "Kırıkkale"),
    ("Kütahya", "Kütahya"),
    ("Malatya", "Malatya"),
    ("Manisa", "Manisa"),
    ("Mardin", "Mardin"),
    ("Mersin", "Mersin"),
    ("Muğla", "Muğla"),
    ("Muş", "Muş"),
    ("Nevşehir", "Nevşehir"),
    ("Niğde", "Niğde"),
    ("Ordu", "Ordu"),
    ("Osmaniye", "Osmaniye"),
    ("Rize", "Rize"),
    ("Sakarya", "Sakarya"),
    ("Samsun", "Samsun"),
    ("Sivas", "Sivas"),
    ("Siirt", "Siirt"),
    ("Sinop", "Sinop"),
    ("İstanbul", "İstanbul"),
    ("Tekirdağ", "Tekirdağ"),
    ("Tokat", "Tokat"),
    ("Trabzon", "Trabzon"),
    ("Tunceli", "Tunceli"),
    ("Uşak", "Uşak"),
    ("Hakkâri", "Hakkâri"),
    ("Hatay", "Hatay"),
    ("Çanakkale", "Çanakkale"),
    ("Çankırı", "Çankırı"),
    ("Çorum", "Çorum"),
    ("Şanlıurfa", "Şanlıurfa"),
    ("Şırnak", "Şırnak"),
    ("Iğdır", "Iğdır"),
    ("Isparta", "Isparta"),
    ("Edirne", "Edirne"),
    ("Elazığ", "Elazığ"),
    ("Erzincan", "Erzincan"),
    ("Erzurum", "Erzurum"),
    ("Eskişehir", "Eskişehir"),
    ("Yalova", "Yalova"),
)


ANTALYA_DIST_LIST = (
    ("Akseki", "Akseki"),
    ("Aksu", "Aksu"),
    ("Alanya", "Alanya"),
    ("Demre", "Demre"),
    ("Döşemealtı", "Döşemealtı"),
    ("Elmalı", "Elmalı"),
    ("Finike", "Finike"),
    ("Gazipaşa", "Gazipaşa"),
    ("Gündoğmuş", "Gündoğmuş"),
    ("İbradı", "İbradı"),
    ("Kaş", "Kaş"),
    ("Kemer", "Kemer"),
    ("Kepez", "Kepez"),
    ("Konyaaltı", "Konyaaltı"),
    ("Korkuteli", "Korkuteli"),
    ("Kumluca", "Kumluca"),
    ("Manavgat", "Manavgat"),
    ("Muratpaşa", "Muratpaşa"),
    ("Serik", "Serik"),
)
