# Generated by Django 4.2.7 on 2023-11-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('APARTMENT', 'Apartment'), ('COMMERS', 'Commercial unit'), ('LAND', 'Land'), ('BUILDING', 'Building'), ('FARM HOUSE', 'Farm house'), ('UNDER CONSTRUCTION', 'Under construction')], default='APARTMENT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NO', 'No Heating'), ('AC', 'Air Conditioner heating'), ('GAS', 'Natural Gas heating'), ('STOVE', 'Fire Place heating'), ('ELECTRIC', 'Electric Boiler heating')], default='NO', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Heating types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='property_imgs')),
                ('rooms', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_site.category')),
                ('heating', models.ForeignKey(default='NO', on_delete=django.db.models.deletion.CASCADE, to='my_site.heating')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ('-created_at',),
            },
        ),
    ]
