# Generated by Django 4.2.7 on 2023-12-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='parking_type',
            new_name='type',
        ),
    ]
