# Generated by Django 4.2.7 on 2023-11-19 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='heating',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('Ağrı', 'Ağrı'), ('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Aydın', 'Aydın'), ('Aksaray', 'Aksaray'), ('Amasya', 'Amasya'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Ardahan', 'Ardahan'), ('Artvin', 'Artvin'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Bayburt', 'Bayburt'), ('Balıkesir', 'Balıkesir'), ('Bartın', 'Bartın'), ('Batman', 'Batman'), ('Bilecik', 'Bilecik'), ('Bingöl', 'Bingöl'), ('Bitlis', 'Bitlis'), ('Bolu', 'Bolu'), ('Burdur', 'Burdur'), ('Bursa', 'Bursa'), ('Van', 'Van'), ('Gaziantep', 'Gaziantep'), ('Giresun', 'Giresun'), ('Gümüşhane', 'Gümüşhane'), ('Denizli', 'Denizli'), ('Diyarbakır', 'Diyarbakır'), ('Düzce', 'Düzce'), ('Zonguldak', 'Zonguldak'), ('İzmir', 'İzmir'), ('Yozgat', 'Yozgat'), ('Kayseri', 'Kayseri'), ('Karabük', 'Karabük'), ('Karaman', 'Karaman'), ('Kars', 'Kars'), ('Kastamonu', 'Kastamonu'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Kilis', 'Kilis'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kırklareli', 'Kırklareli'), ('Kırşehir', 'Kırşehir'), ('Kırıkkale', 'Kırıkkale'), ('Kütahya', 'Kütahya'), ('Malatya', 'Malatya'), ('Manisa', 'Manisa'), ('Mardin', 'Mardin'), ('Mersin', 'Mersin'), ('Muğla', 'Muğla'), ('Muş', 'Muş'), ('Nevşehir', 'Nevşehir'), ('Niğde', 'Niğde'), ('Ordu', 'Ordu'), ('Osmaniye', 'Osmaniye'), ('Rize', 'Rize'), ('Sakarya', 'Sakarya'), ('Samsun', 'Samsun'), ('Sivas', 'Sivas'), ('Siirt', 'Siirt'), ('Sinop', 'Sinop'), ('İstanbul', 'İstanbul'), ('Tekirdağ', 'Tekirdağ'), ('Tokat', 'Tokat'), ('Trabzon', 'Trabzon'), ('Tunceli', 'Tunceli'), ('Uşak', 'Uşak'), ('Hakkâri', 'Hakkâri'), ('Hatay', 'Hatay'), ('Çanakkale', 'Çanakkale'), ('Çankırı', 'Çankırı'), ('Çorum', 'Çorum'), ('Şanlıurfa', 'Şanlıurfa'), ('Şırnak', 'Şırnak'), ('Iğdır', 'Iğdır'), ('Isparta', 'Isparta'), ('Edirne', 'Edirne'), ('Elazığ', 'Elazığ'), ('Erzincan', 'Erzincan'), ('Erzurum', 'Erzurum'), ('Eskişehir', 'Eskişehir'), ('Yalova', 'Yalova')], default='Antalya', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(choices=[('Akseki', 'Akseki'), ('Aksu', 'Aksu'), ('Alanya', 'Alanya'), ('Demre', 'Demre'), ('Döşemealtı', 'Döşemealtı'), ('Elmalı', 'Elmalı'), ('Finike', 'Finike'), ('Gazipaşa', 'Gazipaşa'), ('Gündoğmuş', 'Gündoğmuş'), ('İbradı', 'İbradı'), ('Kaş', 'Kaş'), ('Kemer', 'Kemer'), ('Kepez', 'Kepez'), ('Konyaaltı', 'Konyaaltı'), ('Korkuteli', 'Korkuteli'), ('Kumluca', 'Kumluca'), ('Manavgat', 'Manavgat'), ('Muratpaşa', 'Muratpaşa'), ('Serik', 'Serik')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=models.ForeignKey(default=[1], on_delete=django.db.models.deletion.CASCADE, to='my_site.heating'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
