# Generated by Django 4.2.7 on 2023-11-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_remove_property_city_alter_property_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='img',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='my_site.property')),
            ],
        ),
    ]
