# Generated by Django 4.2.7 on 2023-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_property_elevator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='elevator',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default='NO', max_length=50),
        ),
    ]
