# Generated by Django 4.2.7 on 2023-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_remove_property_img_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='property_imgs'),
        ),
    ]
