# Generated by Django 4.2.7 on 2023-11-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_property_main_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Emlak listesi | Property list'},
        ),
        migrations.AddField(
            model_name='property',
            name='type_of_deel',
            field=models.CharField(blank=True, choices=[('SALE', 'SALE'), ('RENT', 'RENT')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=[1], on_delete=django.db.models.deletion.CASCADE, to='my_site.category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, choices=[('Akseki', 'Akseki'), ('Aksu', 'Aksu'), ('Alanya', 'Alanya'), ('Demre', 'Demre'), ('Döşemealtı', 'Döşemealtı'), ('Elmalı', 'Elmalı'), ('Finike', 'Finike'), ('Gazipaşa', 'Gazipaşa'), ('Gündoğmuş', 'Gündoğmuş'), ('İbradı', 'İbradı'), ('Kaş', 'Kaş'), ('Kemer', 'Kemer'), ('Kepez', 'Kepez'), ('Konyaaltı', 'Konyaaltı'), ('Korkuteli', 'Korkuteli'), ('Kumluca', 'Kumluca'), ('Manavgat', 'Manavgat'), ('Muratpaşa', 'Muratpaşa'), ('Serik', 'Serik')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
