# Generated by Django 4.2.7 on 2023-11-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0006_alter_property_options_property_type_of_deel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type_of_deel',
            new_name='type_of_deal',
        ),
    ]
