# Generated by Django 4.2.7 on 2024-01-04 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0007_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bookmark',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
