# Generated by Django 4.2.7 on 2023-11-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0008_alter_property_type_of_deal_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='main_img',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
