# Generated by Django 4.2.7 on 2024-01-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0012_blog_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ava', models.ImageField(blank=True, default=None, null=True, upload_to='avatars')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
