# Generated by Django 4.2.7 on 2024-01-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0013_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='ava',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='teammates'),
        ),
    ]
