# Generated by Django 4.2.7 on 2024-01-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0015_team_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
