# Generated by Django 4.2.7 on 2024-01-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0016_alter_team_email_alter_team_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
