# Generated by Django 4.2.7 on 2024-01-18 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_site', '0019_remove_profile_follows_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.CharField(max_length=200, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='bookmark'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=[1], on_delete=django.db.models.deletion.CASCADE, to='my_site.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, choices=[('Akseki', 'Akseki'), ('Aksu', 'Aksu'), ('Alanya', 'Alanya'), ('Demre', 'Demre'), ('Döşemealtı', 'Döşemealtı'), ('Elmalı', 'Elmalı'), ('Finike', 'Finike'), ('Gazipaşa', 'Gazipaşa'), ('Gündoğmuş', 'Gündoğmuş'), ('İbradı', 'İbradı'), ('Kaş', 'Kaş'), ('Kemer', 'Kemer'), ('Kepez', 'Kepez'), ('Konyaaltı', 'Konyaaltı'), ('Korkuteli', 'Korkuteli'), ('Kumluca', 'Kumluca'), ('Manavgat', 'Manavgat'), ('Muratpaşa', 'Muratpaşa'), ('Serik', 'Serik')], max_length=50, null=True, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='property',
            name='elevator',
            field=models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], default='No', max_length=50, verbose_name='elevator'),
        ),
        migrations.AlterField(
            model_name='property',
            name='expertise',
            field=models.CharField(blank=True, choices=[('Yes', 'YES'), ('No', 'NO')], default='Yes', max_length=50, null=True, verbose_name='expertise'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor_number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='floor_number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='frontage',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('East', 'East'), ('South', 'South'), ('West', 'West'), ('North-East', 'North-East'), ('South-East', 'South-East'), ('South-West', 'South-West'), ('North-West', 'North-West')], max_length=50, null=True, verbose_name='frontage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=models.ForeignKey(default=[1], on_delete=django.db.models.deletion.CASCADE, to='my_site.heating', verbose_name='heating'),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking',
            field=models.ForeignKey(default=[1], on_delete=django.db.models.deletion.CASCADE, to='my_site.parking', verbose_name='parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.CharField(choices=[('Ağrı', 'Ağrı'), ('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Aydın', 'Aydın'), ('Aksaray', 'Aksaray'), ('Amasya', 'Amasya'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Ardahan', 'Ardahan'), ('Artvin', 'Artvin'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Bayburt', 'Bayburt'), ('Balıkesir', 'Balıkesir'), ('Bartın', 'Bartın'), ('Batman', 'Batman'), ('Bilecik', 'Bilecik'), ('Bingöl', 'Bingöl'), ('Bitlis', 'Bitlis'), ('Bolu', 'Bolu'), ('Burdur', 'Burdur'), ('Bursa', 'Bursa'), ('Van', 'Van'), ('Gaziantep', 'Gaziantep'), ('Giresun', 'Giresun'), ('Gümüşhane', 'Gümüşhane'), ('Denizli', 'Denizli'), ('Diyarbakır', 'Diyarbakır'), ('Düzce', 'Düzce'), ('Zonguldak', 'Zonguldak'), ('İzmir', 'İzmir'), ('Yozgat', 'Yozgat'), ('Kayseri', 'Kayseri'), ('Karabük', 'Karabük'), ('Karaman', 'Karaman'), ('Kars', 'Kars'), ('Kastamonu', 'Kastamonu'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Kilis', 'Kilis'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kırklareli', 'Kırklareli'), ('Kırşehir', 'Kırşehir'), ('Kırıkkale', 'Kırıkkale'), ('Kütahya', 'Kütahya'), ('Malatya', 'Malatya'), ('Manisa', 'Manisa'), ('Mardin', 'Mardin'), ('Mersin', 'Mersin'), ('Muğla', 'Muğla'), ('Muş', 'Muş'), ('Nevşehir', 'Nevşehir'), ('Niğde', 'Niğde'), ('Ordu', 'Ordu'), ('Osmaniye', 'Osmaniye'), ('Rize', 'Rize'), ('Sakarya', 'Sakarya'), ('Samsun', 'Samsun'), ('Sivas', 'Sivas'), ('Siirt', 'Siirt'), ('Sinop', 'Sinop'), ('İstanbul', 'İstanbul'), ('Tekirdağ', 'Tekirdağ'), ('Tokat', 'Tokat'), ('Trabzon', 'Trabzon'), ('Tunceli', 'Tunceli'), ('Uşak', 'Uşak'), ('Hakkâri', 'Hakkâri'), ('Hatay', 'Hatay'), ('Çanakkale', 'Çanakkale'), ('Çankırı', 'Çankırı'), ('Çorum', 'Çorum'), ('Şanlıurfa', 'Şanlıurfa'), ('Şırnak', 'Şırnak'), ('Iğdır', 'Iğdır'), ('Isparta', 'Isparta'), ('Edirne', 'Edirne'), ('Elazığ', 'Elazığ'), ('Erzincan', 'Erzincan'), ('Erzurum', 'Erzurum'), ('Eskişehir', 'Eskişehir'), ('Yalova', 'Yalova')], default='Antalya', max_length=50, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='property',
            name='residence_permit',
            field=models.CharField(blank=True, choices=[('Possible', 'Possible'), ('Not possible', 'Not possible')], default='Not possible', max_length=50, null=True, verbose_name='residence_permit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.CharField(max_length=200, verbose_name='rooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_floors',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='total_floors'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_of_deal',
            field=models.CharField(choices=[('SALE', 'SALE'), ('RENT', 'RENT')], default='SALE', max_length=10, verbose_name='type_of_deal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
