# Generated by Django 4.2.7 on 2024-02-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0021_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Property list'},
        ),
    ]
