# Generated by Django 4.2.7 on 2024-02-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0022_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='en_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='en_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ru_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='ru_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='tr_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
