# Generated by Django 4.2.7 on 2024-07-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0024_blog_de_text_blog_de_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='de_description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='property',
            name='en_description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='property',
            name='ru_description',
            field=models.TextField(default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='property',
            name='tr_description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
